#!/bin/sh

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
    IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

cp $IPKG_OFFLINE_ROOT/etc/event.d/org.daemon.de.netstatd /etc/event.d/org.daemon.de.netstatd

/sbin/start org.daemon.de.netstatd

exit 0
