#!/bin/sh

pidfile="/var/run/netstatd.pid"

if test -s "$pidfile"; then
    pid=`cat $pidfile`
else
    echo "No PID recorded in $pidfile"
    pid=`ps axuw | grep /usr/sbin/netstatd | grep -v grep | awk '{print $2}'`
fi

if test -z "$pid"; then
    echo "/usr/bin/netstatd is not running"
else
    kill $pid
fi


